USE smart_shop;

INSERT INTO categories (id, name) VALUES
(1, 'Smartphones'),
(2, 'Laptops'),
(3, 'Audio'),
(4, 'Wearables'),
(5, 'Tablets'),
(6, 'Gaming'),
(7, 'Cameras'),
(8, 'Smart Home'),
(9, 'Accessories')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Password for both demo users is: password123
INSERT INTO users (id, name, email, password, role) VALUES
(1, 'Admin User', 'admin@smartshop.test', '$2y$10$yFxJevbyfaYPij4XGjaNoeRclb4TZm/N4J9yORR7oSqGJKxB7Hsdq', 'admin'),
(2, 'Student User', 'student@smartshop.test', '$2y$10$yFxJevbyfaYPij4XGjaNoeRclb4TZm/N4J9yORR7oSqGJKxB7Hsdq', 'user')
ON DUPLICATE KEY UPDATE name = VALUES(name), role = VALUES(role);

INSERT INTO products
(id, category_id, brand, model_number, name, description, highlights_json, specs_json, price, original_price, rating, rating_count, stock, image_url, product_url, warranty, shipping_note)
VALUES
(1, 1, 'Apple', 'iPhone 16 128GB', 'Apple iPhone 16', 'A current-generation iPhone with Apple Intelligence support, a durable aluminum design, Camera Control, fast A18 performance, and a balanced camera system for everyday photos and video.', JSON_ARRAY('6.1-inch Super Retina XDR display', 'A18 chip built for Apple Intelligence', '48MP Fusion camera', 'USB-C charging', 'Emergency SOS via satellite'), JSON_OBJECT('Display','6.1-inch Super Retina XDR OLED','Processor','Apple A18','Storage','128GB','Rear camera','48MP Fusion + Ultra Wide','Charging','USB-C','Best for','Everyday flagship phone buyers'), 799.00, 829.00, 4.8, 1842, 18, 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80', 'https://www.apple.com/iphone-16/specs/', '1-year limited manufacturer warranty', 'Free 2-day demo shipping'),
(2, 1, 'Samsung', 'SM-S938U', 'Samsung Galaxy S25 Ultra', 'Premium Android flagship with a large bright display, Galaxy AI features, integrated S Pen, pro-grade zoom camera system, and strong multitasking performance.', JSON_ARRAY('Galaxy AI ready', 'Built-in S Pen', 'Large AMOLED display', 'Pro-grade zoom camera', 'Titanium-style premium build'), JSON_OBJECT('Display','6.9-inch QHD+ AMOLED class','Processor','Snapdragon 8 Elite for Galaxy class','Storage','256GB','Rear camera','200MP wide with telephoto system','Charging','USB-C fast charging','Best for','Power users and mobile photography'), 1299.99, 1419.99, 4.7, 965, 10, 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=80', 'https://www.samsung.com/us/smartphones/galaxy-s25-ultra/', '1-year limited manufacturer warranty', 'Ships in 1 business day'),
(3, 1, 'Google', 'Pixel 9 Pro 128GB', 'Google Pixel 9 Pro', 'Compact pro Pixel phone with Google Tensor performance, advanced AI photo editing, a bright Super Actua display, and long software support.', JSON_ARRAY('Google Tensor G4 class chip', 'Super Actua display', 'Pro triple camera system', '7 years of updates', 'Gemini-powered Pixel features'), JSON_OBJECT('Display','6.3-inch LTPO OLED class','Processor','Google Tensor G4','Storage','128GB','Rear camera','Triple pro camera system','Security','Titan M2 security chip','Best for','AI photos and clean Android'), 999.00, 1099.00, 4.6, 741, 13, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=80', 'https://store.google.com/us/product/pixel_9_pro_specs', '1-year limited manufacturer warranty', 'Pickup available today'),
(4, 1, 'OnePlus', 'CPH2655', 'OnePlus 13', 'Fast Android phone focused on speed, battery life, smooth display performance, and rapid charging for heavy daily users.', JSON_ARRAY('Smooth high-refresh AMOLED display', 'Large battery', 'Fast charging support', 'Flagship-class processor', 'Triple camera system'), JSON_OBJECT('Display','6.8-inch AMOLED class','Processor','Snapdragon 8 Elite class','Storage','256GB','Battery','Large all-day battery','Charging','Fast wired charging','Best for','Performance per dollar'), 899.99, 949.99, 4.5, 318, 16, 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1000&q=80', 'https://www.oneplus.com/us/13', '1-year limited manufacturer warranty', 'Free shipping'),
(5, 2, 'Apple', 'MacBook Air M4 13', 'Apple MacBook Air 13-inch M4', 'Thin and quiet laptop with Apple M4 performance, excellent battery life, a sharp Liquid Retina display, MagSafe, and Thunderbolt ports for school and creative work.', JSON_ARRAY('Apple M4 chip', '13.6-inch Liquid Retina display', 'Fanless silent design', 'MagSafe charging', 'Two Thunderbolt 4 ports'), JSON_OBJECT('Display','13.6-inch Liquid Retina','Processor','Apple M4','Memory','16GB unified memory demo config','Storage','256GB SSD','Ports','MagSafe 3, 2x Thunderbolt 4, headphone jack','Best for','Students, travel, coding, office work'), 999.00, 1099.00, 4.9, 2204, 12, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=80', 'https://www.apple.com/macbook-air/specs/', '1-year limited manufacturer warranty', 'Free 2-day demo shipping'),
(6, 2, 'Dell', 'XPS 13', 'Dell XPS 13', 'Premium Windows ultrabook with compact metal design, bright display options, modern performance, and a clean work-focused layout.', JSON_ARRAY('Compact premium chassis', 'High-resolution display options', 'Fast SSD storage', 'Windows 11 ready', 'Light travel weight'), JSON_OBJECT('Display','13-inch class display','Processor','Intel Core / Snapdragon class options','Memory','16GB demo config','Storage','512GB SSD','Operating system','Windows 11','Best for','Business and productivity'), 1199.00, 1399.00, 4.5, 687, 8, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=80', 'https://www.dell.com/en-us/shop/dell-laptops/xps-13-laptop/spd/xps-13-9350-laptop', '1-year onsite-style demo warranty', 'Ships in 2 business days'),
(7, 2, 'ASUS', 'ROG Zephyrus G14', 'ASUS ROG Zephyrus G14', 'Portable gaming laptop with a high-refresh display, strong GPU performance, and a compact body for gaming, editing, and engineering workloads.', JSON_ARRAY('14-inch high-refresh display', 'NVIDIA GeForce RTX class graphics', 'AMD Ryzen class performance', 'RGB keyboard', 'Portable gaming build'), JSON_OBJECT('Display','14-inch high-refresh panel','Processor','AMD Ryzen class','Graphics','NVIDIA RTX class','Memory','16GB demo config','Storage','1TB SSD','Best for','Gaming and creative work'), 1599.99, 1799.99, 4.6, 492, 7, 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1000&q=80', 'https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g14-series/', '1-year limited manufacturer warranty', 'Signature required'),
(8, 2, 'Lenovo', 'ThinkPad X1 Carbon', 'Lenovo ThinkPad X1 Carbon', 'Business laptop with a durable lightweight design, excellent keyboard, security features, and long battery life for professional users.', JSON_ARRAY('Legendary ThinkPad keyboard', 'Light carbon-fiber class chassis', 'Business security features', 'Long battery life', 'Thunderbolt connectivity'), JSON_OBJECT('Display','14-inch business display','Processor','Intel Core Ultra class','Memory','16GB demo config','Storage','512GB SSD','Security','Fingerprint and camera privacy features','Best for','Business and productivity'), 1399.00, 1649.00, 4.7, 533, 9, 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1000&q=80', 'https://www.lenovo.com/us/en/c/laptops/thinkpad/thinkpadx1/', '3-year business-style demo warranty', 'Ships in 3 business days'),
(9, 5, 'Apple', 'iPad Air 11 M3', 'Apple iPad Air 11-inch', 'Light tablet for school notes, sketching, streaming, and multitasking with Apple Pencil and Magic Keyboard support.', JSON_ARRAY('11-inch Liquid Retina display', 'Apple silicon performance', 'Apple Pencil support', 'Touch ID', 'USB-C'), JSON_OBJECT('Display','11-inch Liquid Retina class','Processor','Apple M-series class','Storage','128GB demo config','Accessories','Apple Pencil and keyboard support','Best for','Students and note-taking'), 599.00, 649.00, 4.8, 1320, 17, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1000&q=80', 'https://www.apple.com/ipad-air/specs/', '1-year limited manufacturer warranty', 'Free shipping'),
(10, 5, 'Samsung', 'Galaxy Tab S10+', 'Samsung Galaxy Tab S10+', 'Large Android tablet with AMOLED display, included-style S Pen experience, multitasking, and strong entertainment features.', JSON_ARRAY('Large AMOLED display', 'S Pen workflow', 'DeX-style multitasking', 'Quad speaker class audio', 'Thin premium body'), JSON_OBJECT('Display','12-inch AMOLED class','Processor','Flagship tablet processor class','Storage','256GB demo config','Input','S Pen support','Best for','Media, notes, and Android multitasking'), 999.99, 1099.99, 4.6, 386, 8, 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=1000&q=80', 'https://www.samsung.com/us/tablets/', '1-year limited manufacturer warranty', 'Pickup available'),
(11, 3, 'Sony', 'WH-1000XM5', 'Sony WH-1000XM5 Wireless Headphones', 'Premium noise-canceling over-ear headphones with LDAC, strong microphone processing, long battery life, and comfortable all-day design.', JSON_ARRAY('Industry-leading noise canceling class', 'LDAC high-resolution wireless audio', 'Up to 30 hours battery class', 'Multipoint Bluetooth', 'Speak-to-chat features'), JSON_OBJECT('Type','Over-ear wireless ANC headphones','Battery','Up to 30 hours class','Codec','LDAC, AAC, SBC','Charging','USB-C','Best for','Travel, focus, and premium music'), 399.99, 429.99, 4.8, 3055, 21, 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=80', 'https://electronics.sony.com/audio/headphones/headband/p/wh1000xm5-b', '1-year limited manufacturer warranty', 'Free 2-day demo shipping'),
(12, 3, 'Apple', 'AirPods Pro 2 USB-C', 'Apple AirPods Pro 2', 'Compact wireless earbuds with active noise cancellation, transparency mode, spatial audio, USB-C charging case, and easy Apple ecosystem pairing.', JSON_ARRAY('Active Noise Cancellation', 'Transparency mode', 'Personalized Spatial Audio', 'USB-C charging case', 'Find My support'), JSON_OBJECT('Type','True wireless earbuds','Chip','Apple H2 class','Charging','USB-C case','Audio','Spatial Audio with dynamic head tracking','Best for','iPhone users and everyday carry'), 249.00, 249.00, 4.8, 5180, 33, 'https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?auto=format&fit=crop&w=1000&q=80', 'https://www.apple.com/airpods-pro/specs/', '1-year limited manufacturer warranty', 'Pickup today'),
(13, 3, 'Bose', 'QuietComfort Ultra', 'Bose QuietComfort Ultra Headphones', 'Comfort-focused premium headphones with immersive audio, excellent noise cancellation, and plush over-ear fit for long listening sessions.', JSON_ARRAY('Immersive audio mode', 'Premium noise cancellation', 'Comfortable over-ear fit', 'Bluetooth multipoint', 'Travel case included'), JSON_OBJECT('Type','Over-ear ANC headphones','Battery','Up to 24 hours class','Charging','USB-C','Audio modes','Quiet, Aware, Immersion','Best for','Comfort and travel'), 429.00, 449.00, 4.7, 1298, 15, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=80', 'https://www.bose.com/p/headphones/bose-quietcomfort-ultra-headphones/QCUH-HEADPHONEARN.html', '1-year limited manufacturer warranty', 'Free shipping'),
(14, 4, 'Apple', 'Watch Series 10', 'Apple Watch Series 10', 'Thin smartwatch with a large bright display, health and fitness features, safety alerts, and tight iPhone integration.', JSON_ARRAY('Large always-on Retina display class', 'Health and fitness tracking', 'Fast charging', 'Water resistance', 'iPhone integration'), JSON_OBJECT('Display','Always-on Retina class','Connectivity','GPS demo config','Health','Heart, sleep, workout tracking','Charging','Fast charging class','Best for','iPhone health and notifications'), 399.00, 429.00, 4.8, 2109, 24, 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=1000&q=80', 'https://www.apple.com/apple-watch-series-10/specs/', '1-year limited manufacturer warranty', 'Ships today'),
(15, 4, 'Samsung', 'Galaxy Watch Ultra', 'Samsung Galaxy Watch Ultra', 'Rugged smartwatch with a bright display, durable build, fitness metrics, and Android-friendly health tracking.', JSON_ARRAY('Rugged watch design', 'Bright outdoor display', 'Fitness and sleep tracking', 'Water-resistant build', 'LTE-style adventure features'), JSON_OBJECT('Display','Outdoor bright AMOLED class','Battery','Multi-day class depending on mode','Health','Fitness, sleep, heart tracking','Compatibility','Android ecosystem','Best for','Outdoor Android users'), 649.99, 699.99, 4.6, 744, 11, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80', 'https://www.samsung.com/us/watches/galaxy-watch-ultra/', '1-year limited manufacturer warranty', 'Free shipping'),
(16, 6, 'Nintendo', 'HEG-001', 'Nintendo Switch OLED Model', 'Hybrid game console with a vibrant 7-inch OLED screen, docked TV play, detachable Joy-Con controllers, and access to Nintendo exclusives.', JSON_ARRAY('7-inch OLED screen', 'TV, tabletop, and handheld modes', '64GB internal storage class', 'Dock with wired LAN port', 'Joy-Con controllers'), JSON_OBJECT('Display','7-inch OLED','Storage','64GB internal class','Modes','TV, tabletop, handheld','Connectivity','Wi-Fi and docked LAN','Best for','Nintendo games and portable play'), 349.99, 349.99, 4.8, 4022, 18, 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=1000&q=80', 'https://www.nintendo.com/us/gaming-systems/switch/tech-specs/', '1-year limited manufacturer warranty', 'Pickup available'),
(17, 6, 'Sony', 'CFI-2000', 'PlayStation 5 Slim Console', 'Current slim PlayStation 5 console with fast SSD storage, DualSense controller, 4K gaming support, and access to PS5 exclusives.', JSON_ARRAY('Slim PS5 design', 'Ultra-high speed SSD', 'DualSense wireless controller', '4K gaming support', 'Backward compatible PS4 library'), JSON_OBJECT('Storage','1TB SSD class','Resolution','Up to 4K gaming class','Controller','DualSense wireless controller','Edition','Disc console demo config','Best for','Console gaming and exclusives'), 499.99, 499.99, 4.9, 6511, 9, 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1000&q=80', 'https://www.playstation.com/en-us/ps5/', '1-year limited manufacturer warranty', 'Signature required'),
(18, 6, 'Microsoft', 'Xbox Series X', 'Xbox Series X', 'Powerful Xbox console with fast SSD storage, 4K gaming support, Game Pass access, and broad backward compatibility.', JSON_ARRAY('4K gaming class performance', 'Fast SSD storage', 'Quick Resume', 'Game Pass ready', 'Backward compatibility'), JSON_OBJECT('Storage','1TB SSD class','Resolution','Up to 4K gaming class','Controller','Xbox Wireless Controller','Subscription','Game Pass compatible','Best for','Xbox ecosystem and Game Pass'), 499.99, 499.99, 4.8, 3990, 12, 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1000&q=80', 'https://www.xbox.com/en-US/consoles/xbox-series-x', '1-year limited manufacturer warranty', 'Free shipping'),
(19, 7, 'Sony', 'ZV-E10 II', 'Sony ZV-E10 II Creator Camera', 'Compact interchangeable-lens camera for creators with strong video tools, flip screen, product showcase style shooting, and high-quality APS-C imaging.', JSON_ARRAY('APS-C interchangeable-lens camera', 'Creator-focused video tools', 'Flip-out screen', 'USB streaming support', 'Compact body'), JSON_OBJECT('Sensor','APS-C class','Lens mount','Sony E-mount','Video','4K creator video class','Screen','Vari-angle display','Best for','YouTube, streaming, and content creation'), 999.99, 1099.99, 4.6, 284, 6, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1000&q=80', 'https://electronics.sony.com/imaging/interchangeable-lens-cameras/aps-c/p/zve10m2-b', '1-year limited manufacturer warranty', 'Ships in 2 business days'),
(20, 7, 'Canon', 'EOS R50', 'Canon EOS R50 Mirrorless Camera', 'Beginner-friendly mirrorless camera with sharp stills, 4K video class capture, subject detection autofocus, and compact design for travel and creators.', JSON_ARRAY('Mirrorless camera body', 'Subject detection autofocus', '4K video class recording', 'Vari-angle touchscreen', 'Compact travel size'), JSON_OBJECT('Sensor','APS-C class','Lens mount','Canon RF mount','Video','4K video class','Screen','Vari-angle touchscreen','Best for','Beginner creators and travel'), 679.99, 799.99, 4.7, 624, 8, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1000&q=80', 'https://www.usa.canon.com/shop/p/eos-r50', '1-year limited manufacturer warranty', 'Free shipping'),
(21, 8, 'Amazon', 'Kindle Paperwhite Signature', 'Kindle Paperwhite Signature Edition', 'Water-resistant e-reader with a crisp glare-free display, warm light, wireless charging support, and large storage for books.', JSON_ARRAY('Glare-free Paperwhite display', 'Adjustable warm light', 'Water-resistant design', 'Wireless charging support', 'Large book storage'), JSON_OBJECT('Display','Paperwhite e-ink display class','Storage','32GB class','Lighting','Adjustable warm light','Charging','USB-C and wireless charging support','Best for','Reading and travel'), 189.99, 199.99, 4.7, 2890, 20, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80', 'https://www.amazon.com/kindle-paperwhite-signature-edition/', '1-year limited manufacturer warranty', 'Free shipping'),
(22, 8, 'Ring', 'Battery Doorbell Pro', 'Ring Battery Doorbell Pro', 'Smart video doorbell with battery power, motion alerts, head-to-toe video style coverage, and app-based visitor monitoring.', JSON_ARRAY('Battery-powered video doorbell', 'Motion alerts', 'Two-way talk', 'Head-to-toe video class view', 'Smart home app integration'), JSON_OBJECT('Power','Rechargeable battery','Video','HD video class','Audio','Two-way talk','Connectivity','Wi-Fi','Best for','Apartment and home entry monitoring'), 229.99, 249.99, 4.5, 1187, 14, 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1000&q=80', 'https://ring.com/products/battery-doorbell-pro', '1-year limited manufacturer warranty', 'Ships today'),
(23, 9, 'Anker', 'PowerCore 24K 737', 'Anker 737 Power Bank', 'High-capacity USB-C power bank for laptops, tablets, phones, and travel, with fast charging output and a useful status display.', JSON_ARRAY('High-capacity portable charging', 'USB-C laptop charging class', 'Smart status display', 'Multiple device outputs', 'Travel-friendly backup power'), JSON_OBJECT('Capacity','24,000mAh class','Ports','USB-C and USB-A class outputs','Display','Charging status screen','Best for','Travel and laptop backup power'), 149.99, 179.99, 4.7, 2011, 26, 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=1000&q=80', 'https://www.anker.com/products/a1289', '18-month limited manufacturer warranty', 'Free shipping'),
(24, 9, 'Logitech', 'MX Master 3S', 'Logitech MX Master 3S Mouse', 'Premium productivity mouse with quiet clicks, MagSpeed scrolling, ergonomic shape, multi-device pairing, and precise tracking.', JSON_ARRAY('Quiet tactile clicks', 'MagSpeed scroll wheel', 'Ergonomic hand shape', 'Multi-device Bluetooth', 'High-precision sensor'), JSON_OBJECT('Connectivity','Bluetooth and USB receiver class','Sensor','8K DPI class','Battery','Rechargeable USB-C','Compatibility','Windows, macOS, Linux class','Best for','Productivity and creative work'), 99.99, 109.99, 4.8, 3560, 35, 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1000&q=80', 'https://www.logitech.com/en-us/products/mice/mx-master-3s.html', '1-year limited manufacturer warranty', 'Pickup available today')
ON DUPLICATE KEY UPDATE
category_id = VALUES(category_id),
brand = VALUES(brand),
model_number = VALUES(model_number),
name = VALUES(name),
description = VALUES(description),
highlights_json = VALUES(highlights_json),
specs_json = VALUES(specs_json),
price = VALUES(price),
original_price = VALUES(original_price),
rating = VALUES(rating),
rating_count = VALUES(rating_count),
stock = VALUES(stock),
image_url = VALUES(image_url),
product_url = VALUES(product_url),
warranty = VALUES(warranty),
shipping_note = VALUES(shipping_note);

